apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-logger
  template:
    metadata:
      labels:
        app: mqtt-logger
    spec:
      containers:
      - name: mqtt-logger
        image: moreillon/mqtt-logger:ff648578
        env:
        # InfluxDB
        - name: INFLUXDB_URL
          value: http://influxdb
        - name: INFLUXDB_TOKEN
          value: {{ .Values.influxdb.token }}
        - name: INFLUXDB_ORG
          value: {{ .Values.influxdb.org }}
        - name: INFLUXDB_BUCKET
          value: {{ .Values.influxdb.bucket }}
        # MongoDB
        - name: MONGODB_URL
          value: mongodb://mongo
        # MQTT
        - name: MQTT_URL
          value: {{ .Values.mqtt.broker }}
        - name: MQTT_USERNAME
          value: {{ .Values.credentials.username }}
        - name: MQTT_PASSWORD
          value: {{ .Values.credentials.password }}
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-logger
spec:
  type: NodePort
  selector:
    app: mqtt-logger
  ports:
  - port: 80
    nodePort: 31882
